config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :agencies

  resources :receivers

  resources :alerts

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/receiver.rb
class Receiver < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tone_sets
  
  
  def to_s
    self.common_name + " " + self.frequency.to_s
  end
end

app/controllers/receivers_controller.rb
class ReceiversController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_receiver, only: [:show, :edit, :update, :destroy]

  # GET /receivers
  # GET /receivers.json
  def index
    @receivers = Receiver.all
  end

  # GET /receivers/1
  # GET /receivers/1.json
  def show
  end

  # GET /receivers/new
  def new
    @receiver = Receiver.new
  end

  # GET /receivers/1/edit
  def edit
  end

  # POST /receivers
  # POST /receivers.json
  def create
    @receiver = Receiver.new(receiver_params)
    @receiver.user = current_user

    respond_to do |format|
      if @receiver.save
        format.html { redirect_to @receiver, notice: 'Receiver was successfully created.' }
        format.json { render :show, status: :created, location: @receiver }
      else
        format.html { render :new }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receivers/1
  # PATCH/PUT /receivers/1.json
  def update
    respond_to do |format|
      if @receiver.update(receiver_params)
        format.html { redirect_to @receiver, notice: 'Receiver was successfully updated.' }
        format.json { render :show, status: :ok, location: @receiver }
      else
        format.html { render :edit }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receivers/1
  # DELETE /receivers/1.json
  def destroy
    @receiver.destroy
    respond_to do |format|
      format.html { redirect_to receivers_url, notice: 'Receiver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receiver
      @receiver = Receiver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receiver_params
      params.require(:receiver).permit(:location, :frequency, :user_id, :latitude, :longitude, :haat)
    end
end

app/helpers/receivers_helper.rb
module ReceiversHelper
end

app/views/receivers/_form.html.erb
<%= form_for @receiver, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :location, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :frequency, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :frequency, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :latitude, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :latitude, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :longitude, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :haat, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :haat, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  receivers_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/receivers/edit.html.erb
<%- model_class = Receiver -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Receiver %></h1>
</div>
<%= render :partial => 'form' %>

app/views/receivers/index.html.erb
<%- model_class = Receiver -%>
<div class="page-header">
  <h1><%=t '.title', :default => Receiver %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:frequency) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:haat) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @receivers.each do |receiver| %>
      <tr>
        <td><%= receiver.id %></td>
        <td><%= receiver.location %></td>
        <td><%= receiver.frequency %></td>
        <td><%= receiver.latitude %></td>
        <td><%= receiver.longitude %></td>
        <td><%= receiver.haat %></td>
        <td><%=l receiver.created_at, format: :long %></td>
        <td>
          <%= link_to receiver_path(receiver), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to receiver_path(receiver), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_receiver_path,
            :class => 'btn btn-primary' %>

app/views/receivers/new.html.erb
<%- model_class = Receiver -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Receiver %></h1>
</div>
<%= render :partial => 'form' %>

app/views/receivers/show.html.erb
<%- model_class = Receiver -%>
<div class="page-header">
  <h1><%=t '.title', :default => Receiver %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:location) %></dt>
      <dd><pre class="prettyprint"><%= @receiver.location %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:frequency) %></dt>
      <dd><pre class="prettyprint"><%= @receiver.frequency %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:latitude) %></dt>
      <dd><pre class="prettyprint"><%= @receiver.latitude %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:longitude) %></dt>
      <dd><pre class="prettyprint"><%= @receiver.longitude %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:haat) %></dt>
      <dd><pre class="prettyprint"><%= @receiver.haat %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              receivers_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_receiver_path(@receiver), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              receiver_path(@receiver),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/receivers/show.text.erb
<%
i = 0
 @receiver.tone_sets.each do |f| 
 if !f.long_tone.blank? %>
[Longtone<%= i += 1 %>]
Longtone = <%= f.long_tone %>
Longtonelength = <%= f.long_tone_time %>
<% elsif !f.a_tone.blank? && !f.b_tone.blank? %>
[Tone<%=  i += 1 %>]
Atone = <%= f.a_tone %>
Btone = <%= f.b_tone %>
Atonelength = <%= f.a_tone_time || ".5" rescue ".5" %>
Btonelength = <%= f.b_tone_time || "1.2" rescue "1.2" %>
<%end %>
Description = <%= f.agency.title rescue "Unknown Agency" %>
record_delay = <%= f.record_delay rescue "2.5" %>
ignore_after = <%= f.ignore_after rescue "60" %>
<%= f.mp3_emails rescue "" %>
<%= f.text_emails rescue "" %>

<% end%>